# Copyright (c) Siemens Mobility A/S 2024, All Rights Reserved - CONFIDENTIAL
include:
  - project: 'smo-denmark/devops/pipelines/docker'
    file: 'artifactory.yml'

build:
  image: artifacts.mobility.siemens.com/dk_smo_sw-docker-development-local/smo-denmark/commercial-projects/hovedstadens-letbane/clris/artifacts/ipxe
  script:
    - cd src || exit 1
    - echo "#define DOWNLOAD_PROTO_NFS" >>config/general.h
    - make bin-x86_64-efi/ipxe.efi EMBED=clris.ipxe
    - cp bin-x86_64-efi/ipxe.efi ../
  artifacts:
    paths:
      - src/bin-x86_64-efi/ipxe.efi
