# Copyright (c) Siemens Mobility A/S 2024, All Rights Reserved - CONFIDENTIAL
include:
  - project: 'smo-denmark/devops/pipelines/docker'
    file: 'artifactory.yml'

build:
  image: artifacts.mobility.siemens.com/smo-denmark/data-integration-analysis/projects/letbane-paa-ring-3/clris/artifacts/ipxe:latest
  needs: [docker-deploy-development]
  script:
    - make ipxe.efi
  artifacts:
    paths:
      - ipxe.efi
      - src/clris.ipxe
