# Copyright (c) Siemens Mobility A/S 2024, All Rights Reserved - CONFIDENTIAL
build:
  image: artifacts.mobility.siemens.com/dk_smo_sw-docker-development-local/smo-denmark/devops/docker-images/debian:bookworm
  script:
    - apt update
    - "apt install -y mtools syslinux isolinux libc6-dev-i386 libgcc-s1:i386 libc6-dbg:i386"
    - cd src || exit 1
    - echo "#define DOWNLOAD_PROTO_NFS" >>config/general.h
    - make -j 4 bin-x86_64-efi/ipxe.efi EMBED=clris.ipxe
    - cp bin-x86_64-efi/ipxe.efi ../
  artifacts:
    paths:
      - src/bin-x86_64-efi/ipxe.efi
