# Copyright (c) Siemens Mobility A/S 2024, All Rights Reserved - CONFIDENTIAL
include:
  - project: 'smo-denmark/devops/pipelines/docker'
    file: 'artifactory.yml'

build:
  image: artifacts.mobility.siemens.com/smo-denmark/data-integration-analysis/projects/letbane-paa-ring-3/clris/artifacts/ipxe:latest
  needs: [docker-deploy-development]
  script:
    - cd src || exit 1
    - echo "#define DOWNLOAD_PROTO_NFS" >>config/general.h
    - make -j 4 bin-x86_64-efi/ipxe.efi EMBED=clris.ipxe
    - cp bin-x86_64-efi/ipxe.efi ../
  artifacts:
    paths:
      - src/bin-x86_64-efi/ipxe.efi
      - src/clris.ipxe
